// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEN5rlVs5JUT6c54dXXk-zrKh-nr1t2os',
    appId: '1:717631142117:web:036b41da1496a70d14bc0c',
    messagingSenderId: '717631142117',
    projectId: 'newapp-e317e',
    authDomain: 'newapp-e317e.firebaseapp.com',
    storageBucket: 'newapp-e317e.appspot.com',
    measurementId: 'G-5GBRLP9VBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRbPIzJ41taOwY2X5YUr0uO5whj0CJtik',
    appId: '1:717631142117:android:60be3880e2a2f36314bc0c',
    messagingSenderId: '717631142117',
    projectId: 'newapp-e317e',
    storageBucket: 'newapp-e317e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4W847GWx5niMUIClisZUPqsApHoJAh-M',
    appId: '1:717631142117:ios:711373ce8831bfe314bc0c',
    messagingSenderId: '717631142117',
    projectId: 'newapp-e317e',
    storageBucket: 'newapp-e317e.appspot.com',
    iosBundleId: 'com.example.connectify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4W847GWx5niMUIClisZUPqsApHoJAh-M',
    appId: '1:717631142117:ios:711373ce8831bfe314bc0c',
    messagingSenderId: '717631142117',
    projectId: 'newapp-e317e',
    storageBucket: 'newapp-e317e.appspot.com',
    iosBundleId: 'com.example.connectify',
  );
}
